# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/pipeline/inhouse/DCC/maya/int/modules/rigging/mbox/python/mbox/lego/namingrulesdesign.ui',
# licensing of 'D:/pipeline/inhouse/DCC/maya/int/modules/rigging/mbox/python/mbox/lego/namingrulesdesign.ui' applies.
#
# Created: Mon Jul  5 20:41:05 2021
#      by: pyside2-uic  running on PySide2 5.12.5
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(359, 344)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_8 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.common_name_rule_lineEdit = QtWidgets.QLineEdit(self.groupBox_8)
        self.common_name_rule_lineEdit.setObjectName("common_name_rule_lineEdit")
        self.horizontalLayout.addWidget(self.common_name_rule_lineEdit)
        self.reset_common_name_rule_pushButton = QtWidgets.QPushButton(self.groupBox_8)
        self.reset_common_name_rule_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.reset_common_name_rule_pushButton.setObjectName("reset_common_name_rule_pushButton")
        self.horizontalLayout.addWidget(self.reset_common_name_rule_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.common_des_letter_case_comboBox = QtWidgets.QComboBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.common_des_letter_case_comboBox.sizePolicy().hasHeightForWidth())
        self.common_des_letter_case_comboBox.setSizePolicy(sizePolicy)
        self.common_des_letter_case_comboBox.setObjectName("common_des_letter_case_comboBox")
        self.common_des_letter_case_comboBox.addItem("")
        self.common_des_letter_case_comboBox.addItem("")
        self.common_des_letter_case_comboBox.addItem("")
        self.common_des_letter_case_comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.common_des_letter_case_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.groupBox_8)
        self.groupBox_9 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.joint_name_rule_lineEdit = QtWidgets.QLineEdit(self.groupBox_9)
        self.joint_name_rule_lineEdit.setObjectName("joint_name_rule_lineEdit")
        self.horizontalLayout_2.addWidget(self.joint_name_rule_lineEdit)
        self.reset_joint_name_rule_pushButton = QtWidgets.QPushButton(self.groupBox_9)
        self.reset_joint_name_rule_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.reset_joint_name_rule_pushButton.setObjectName("reset_joint_name_rule_pushButton")
        self.horizontalLayout_2.addWidget(self.reset_joint_name_rule_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.joint_des_letter_case_comboBox = QtWidgets.QComboBox(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.joint_des_letter_case_comboBox.sizePolicy().hasHeightForWidth())
        self.joint_des_letter_case_comboBox.setSizePolicy(sizePolicy)
        self.joint_des_letter_case_comboBox.setObjectName("joint_des_letter_case_comboBox")
        self.joint_des_letter_case_comboBox.addItem("")
        self.joint_des_letter_case_comboBox.addItem("")
        self.joint_des_letter_case_comboBox.addItem("")
        self.joint_des_letter_case_comboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.joint_des_letter_case_comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addWidget(self.groupBox_9)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_10 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setObjectName("groupBox_10")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_10)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.direction_left_name_lineEdit = QtWidgets.QLineEdit(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.direction_left_name_lineEdit.sizePolicy().hasHeightForWidth())
        self.direction_left_name_lineEdit.setSizePolicy(sizePolicy)
        self.direction_left_name_lineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.direction_left_name_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.direction_left_name_lineEdit.setObjectName("direction_left_name_lineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.direction_left_name_lineEdit)
        self.label_5 = QtWidgets.QLabel(self.groupBox_10)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.direction_right_name_lineEdit = QtWidgets.QLineEdit(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.direction_right_name_lineEdit.sizePolicy().hasHeightForWidth())
        self.direction_right_name_lineEdit.setSizePolicy(sizePolicy)
        self.direction_right_name_lineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.direction_right_name_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.direction_right_name_lineEdit.setObjectName("direction_right_name_lineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.direction_right_name_lineEdit)
        self.label_6 = QtWidgets.QLabel(self.groupBox_10)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.direction_center_name_lineEdit = QtWidgets.QLineEdit(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.direction_center_name_lineEdit.sizePolicy().hasHeightForWidth())
        self.direction_center_name_lineEdit.setSizePolicy(sizePolicy)
        self.direction_center_name_lineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.direction_center_name_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.direction_center_name_lineEdit.setObjectName("direction_center_name_lineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.direction_center_name_lineEdit)
        self.reset_side_name_pushButton = QtWidgets.QPushButton(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_side_name_pushButton.sizePolicy().hasHeightForWidth())
        self.reset_side_name_pushButton.setSizePolicy(sizePolicy)
        self.reset_side_name_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.reset_side_name_pushButton.setObjectName("reset_side_name_pushButton")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.reset_side_name_pushButton)
        self.gridLayout.addWidget(self.groupBox_10, 0, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_11.sizePolicy().hasHeightForWidth())
        self.groupBox_11.setSizePolicy(sizePolicy)
        self.groupBox_11.setObjectName("groupBox_11")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_11)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_11)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.ctl_name_ext_lineEdit = QtWidgets.QLineEdit(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctl_name_ext_lineEdit.sizePolicy().hasHeightForWidth())
        self.ctl_name_ext_lineEdit.setSizePolicy(sizePolicy)
        self.ctl_name_ext_lineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.ctl_name_ext_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ctl_name_ext_lineEdit.setObjectName("ctl_name_ext_lineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ctl_name_ext_lineEdit)
        self.label_8 = QtWidgets.QLabel(self.groupBox_11)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.joint_name_ext_lineEdit = QtWidgets.QLineEdit(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.joint_name_ext_lineEdit.sizePolicy().hasHeightForWidth())
        self.joint_name_ext_lineEdit.setSizePolicy(sizePolicy)
        self.joint_name_ext_lineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.joint_name_ext_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.joint_name_ext_lineEdit.setObjectName("joint_name_ext_lineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.joint_name_ext_lineEdit)
        self.reset_name_ext_pushButton = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_name_ext_pushButton.sizePolicy().hasHeightForWidth())
        self.reset_name_ext_pushButton.setSizePolicy(sizePolicy)
        self.reset_name_ext_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.reset_name_ext_pushButton.setObjectName("reset_name_ext_pushButton")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.reset_name_ext_pushButton)
        self.gridLayout.addWidget(self.groupBox_11, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 10000, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.groupBox_8.setTitle(QtWidgets.QApplication.translate("Form", "Common Naming Rule", None, -1))
        self.common_name_rule_lineEdit.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Custom Naming rule:</span></p><p>To configure custom names, please use the following tokes with &quot;<span style=\" font-weight:600;\">{}</span>&quot;</p><p><br/></p><p><span style=\" font-weight:600;\">{component}</span> = The name of the component</p><p><span style=\" font-weight:600;\">{side}</span> = The side of the component</p><p><span style=\" font-weight:600;\">{index</span>} = Index of the component. This is important when more than one component have the same name</p><p><span style=\" font-weight:600;\">{description}</span> = The name of the object inside the component</p><p><span style=\" font-weight:600;\">{extension}</span> = The extension of the object. For example &quot;ctl&quot; for controls or &quot;jnt&quot; for joints</p><p><br/></p><p><span style=\" font-weight:600;\">NOTE:</span> the only valid separator is &quot;_&quot;. This is a Maya limitation.</p><p><br/></p><p><br/></p><p><span style=\" font-weight:600;\">This is the default configuration:</span></p><p>{component}_{side}{index}_{description}_{extension}</p><p><br/></p><p><br/></p><p><span style=\" font-weight:600;\">Other examples of configurations:</span></p><p>{component}{side}{index}{description}{extension}</p><p>{component}{index}_{description}_{extension}_{side}</p><p>{component}{index}_some_random_text_{description}_{extension}_{side}</p><p><br/></p><p><span style=\" font-weight:600;\">It is recommended to use all the tokens to ensure that there is no name clashing</span></p></body></html>", None, -1))
        self.common_name_rule_lineEdit.setText(QtWidgets.QApplication.translate("Form", "{component}_{side}{index}_{description}_{extension}", None, -1))
        self.reset_common_name_rule_pushButton.setText(QtWidgets.QApplication.translate("Form", "Reset", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "{descrition} Letter Case", None, -1))
        self.common_des_letter_case_comboBox.setItemText(0, QtWidgets.QApplication.translate("Form", "Default", None, -1))
        self.common_des_letter_case_comboBox.setItemText(1, QtWidgets.QApplication.translate("Form", "Upper Case", None, -1))
        self.common_des_letter_case_comboBox.setItemText(2, QtWidgets.QApplication.translate("Form", "Lower Case", None, -1))
        self.common_des_letter_case_comboBox.setItemText(3, QtWidgets.QApplication.translate("Form", "Capitalization", None, -1))
        self.groupBox_9.setTitle(QtWidgets.QApplication.translate("Form", "Joints Naming Rule", None, -1))
        self.joint_name_rule_lineEdit.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Custom Naming rule:</span></p><p>To configure custom names, please use the following tokes with &quot;<span style=\" font-weight:600;\">{}</span>&quot;</p><p><br/></p><p><span style=\" font-weight:600;\">{component}</span> = The name of the component</p><p><span style=\" font-weight:600;\">{side}</span> = The side of the component</p><p><span style=\" font-weight:600;\">{index</span>} = Index of the component. This is important when more than one component have the same name</p><p><span style=\" font-weight:600;\">{description}</span> = The name of the object inside the component</p><p><span style=\" font-weight:600;\">{extension}</span> = The extension of the object. For example &quot;ctl&quot; for controls or &quot;jnt&quot; for joints</p><p><br/></p><p><span style=\" font-weight:600;\">NOTE:</span> the only valid separator is &quot;_&quot;. This is a Maya limitation.</p><p><br/></p><p><br/></p><p><span style=\" font-weight:600;\">This is the default configuration:</span></p><p>{component}_{side}{index}_{description}_{extension}</p><p><br/></p><p><br/></p><p><span style=\" font-weight:600;\">Other examples of configurations:</span></p><p>{component}{side}{index}{description}{extension}</p><p>{component}{index}_{description}_{extension}_{side}</p><p>{component}{index}_some_random_text_{description}_{extension}_{side}</p><p><br/></p><p><span style=\" font-weight:600;\">It is recommended to use all the tokens to ensure that there is no name clashing</span></p></body></html>", None, -1))
        self.joint_name_rule_lineEdit.setText(QtWidgets.QApplication.translate("Form", "{component}_{side}{index}_{description}_{extension}", None, -1))
        self.reset_joint_name_rule_pushButton.setText(QtWidgets.QApplication.translate("Form", "Reset", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "{descrition} Letter Case", None, -1))
        self.joint_des_letter_case_comboBox.setItemText(0, QtWidgets.QApplication.translate("Form", "Default", None, -1))
        self.joint_des_letter_case_comboBox.setItemText(1, QtWidgets.QApplication.translate("Form", "Upper Case", None, -1))
        self.joint_des_letter_case_comboBox.setItemText(2, QtWidgets.QApplication.translate("Form", "Lower Case", None, -1))
        self.joint_des_letter_case_comboBox.setItemText(3, QtWidgets.QApplication.translate("Form", "Capitalization", None, -1))
        self.groupBox_10.setTitle(QtWidgets.QApplication.translate("Form", "direction Naming", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "Left", None, -1))
        self.direction_left_name_lineEdit.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>set the text that will be used for the side:</p><p><br/></p><p><span style=\" font-weight:600;\">for example:</span></p><p>L</p><p>left</p><p>Left</p><p>l</p><p><br/></p><p>r</p><p>right</p><p>Right</p><p>Derecha</p><p>R</p><p><br/></p><p><br/></p></body></html>", None, -1))
        self.direction_left_name_lineEdit.setText(QtWidgets.QApplication.translate("Form", "L", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "Right", None, -1))
        self.direction_right_name_lineEdit.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>set the text that will be used for the side:</p><p><br/></p><p><span style=\" font-weight:600;\">for example:</span></p><p>L</p><p>left</p><p>Left</p><p>l</p><p><br/></p><p>r</p><p>right</p><p>Right</p><p>Derecha</p><p>R</p><p><br/></p><p><br/></p></body></html>", None, -1))
        self.direction_right_name_lineEdit.setText(QtWidgets.QApplication.translate("Form", "R", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Form", "Center", None, -1))
        self.direction_center_name_lineEdit.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>set the text that will be used for the side:</p><p><br/></p><p><span style=\" font-weight:600;\">for example:</span></p><p>L</p><p>left</p><p>Left</p><p>l</p><p><br/></p><p>r</p><p>right</p><p>Right</p><p>Derecha</p><p>R</p><p><br/></p><p><br/></p></body></html>", None, -1))
        self.direction_center_name_lineEdit.setText(QtWidgets.QApplication.translate("Form", "C", None, -1))
        self.reset_side_name_pushButton.setText(QtWidgets.QApplication.translate("Form", "Reset", None, -1))
        self.groupBox_11.setTitle(QtWidgets.QApplication.translate("Form", "Extensions Naming", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Form", "Controls", None, -1))
        self.ctl_name_ext_lineEdit.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>Set the extension name for controls</p><p><br/></p><p><span style=\" font-weight:600;\">For example:</span></p><p>ctl</p><p>control</p><p>mover</p><p>ct</p><p>etc..</p></body></html>", None, -1))
        self.ctl_name_ext_lineEdit.setText(QtWidgets.QApplication.translate("Form", "ctl", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Form", "Joints", None, -1))
        self.joint_name_ext_lineEdit.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>Set the extension name for joints</p><p><br/></p><p><span style=\" font-weight:600;\">For example:</span></p><p>jnt</p><p>joint</p><p>bone</p><p>j</p><p>etc..</p></body></html>", None, -1))
        self.joint_name_ext_lineEdit.setText(QtWidgets.QApplication.translate("Form", "jnt", None, -1))
        self.reset_name_ext_pushButton.setText(QtWidgets.QApplication.translate("Form", "Reset", None, -1))

